# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Ngô Phước Thành
title: Student at UEH University
email: ngophuocthanh2005@gmail.com
# email_title: Email (Email title override)
phone: 0843434151
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  npthah
facebook_username: phuoc.thanh.314329
instagram_username: np._.thah
linkedin_username: phước-thành-56930435a/
orcid_username: 0009-0005-6108-3748

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/tom.jpg
about_content: | # this will include new lines to allow paragraphs
 As a student at the **UEH University**, I am pursuing a dual major in **Investment Economics** and **Financial Technology (Fintech)**.
 
 I am deeply passionate about the intersection of **technology** and **business**, particularly how technology can optimize financial and investment decisions.
 
 I am a highly responsible and eager learner, actively seeking new opportunities to challenge myself and apply my knowledge to real-world scenarios.

content:
 - title: Education # --- EDUCATION SECTION ---
   layout: list
   content:
    - layout: top-right
      

content:
  - title: Education # --- EDUCATION SECTION ---
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        title: University of Economics Ho Chi Minh City (UEH)
        sub_title: Bachelor's Degree, Dual Major in Investment Economics & Fintech
        caption: 2023 - 2028 (Expected)
        quote: >
        3rd Year Student, High-Quality Bachelor's Program.
        description: | # Additional description
          * Current GPA: 3.7
          * Relevant Coursework: Portfolio Management, Financial Analysis, Applied Python Programming.
  
  - title: Experience # --- EXPERIENCE SECTION ---
    layout: list
    content:
    - layout: right
      title: BELL Club (UEH)
      sub_title: HR Teams
      quote: >
        Actively participated in internal activities and club campaigns.
      description: | 
        * **Finance Team:** Assisted in budgeting and financial planning for internal club activities.
        * **Design Team (Summer Volunteer Campaign 2024):** Led the design of posters, banners, and communication materials for the campaign.

    - layout: left
      title: Investment Portfolio Management Project (Coursework)
      quote: >
        Achieved an A+ grade for this major-specific project.
      description: | 
        * Applied theoretical models for asset analysis and selection.
        * Built and optimized a simulated investment portfolio, focusing on risk management.
        * Utilized Python and Stata for data analysis and strategy back-testing.
 
    - layout: right
      title: Academic Competitions
      description: | 
        * Participant in university-level competitions: **CELG**, **UEH Young Researcher**.
        * Participant in the **Seed of Changes** competition, organized by the Institute of Innovation (UII).

  - title: Certifications # --- CERTIFICATIONS SECTION ---
    layout: list
    content:
      - layout: left
        border: weak
        title: IELTS 6.5
        description: |
          Valid international English language proficiency certificate.
      - layout: left
        title: MOS (Microsoft Office Specialist)
        description: |
          Certification for expert-level skills in Microsoft Office (Word, Excel, PowerPoint).

  - title: Skills # --- SKILLS SECTION ---
    layout: text
    content: | # Your skills
      **Hard Skills:**
      * Languages/Software: **Python**, **Stata**, **Adobe Photoshop**.
      * Finance: Financial Statement Analysis, Portfolio Management.
      * Office Suite: Proficient in Microsoft Office (Advanced Excel).
 
      **Soft Skills:**
      * Communication & Presentation (Good).
      * Critical Thinking.
      * High Responsibility, Eager to Learn.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
